### PR TITLE
fix: Correct center frequency #6

### PR DESCRIPTION
**Pull request by wildintellect**
Before you submit a pull request, please fill in the following:

**Related Issue(s):**
Please add links (if any) to related github issues.
#6 

**Description:**
Please explain the changes you made here.
Updated the Center Frequency value based on review from JAXA.
Did not think this warranted a Changelog entry as the package is unreleased and minor corrections were expected.

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [x] Documentation has been updated to reflect changes, if applicable.
- [x] Examples have been updated to reflect changes, if applicable
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

### CODE REVIEW

**Review by gadomski — APPROVED** [review]
Is this documented anywhere we can reference?

**Comment by wildintellect** [comment]
@gadomski yes there's ticket #6

**Comment by gadomski** [comment]
I guess I meant something from the data provider, like a user handbook that lists the value?

**Comment by wildintellect** [comment]
@gadomski I have not been able to find it in any of the Handbooks, this particular value used here came from the XML metadata provided with the items (as noted in https://www.eorc.jaxa.jp/ALOS/en/dataset/pdf/PALSAR2_CARD4L_L2.2_Geotiff_Format_Description_E_20220715.pdf) and was confirmed by email from JAXA (Shin-ichi the lead on the data distribution).  I will ask if any other frequencies are possible since the sensor does seem to capable of it.

**Comment by gadomski** [comment]
Ok, yeah no worries, it's just nice to add traceability whenever possible. If it's too much of a lift no worries.

**Pull request merged**
